---
blank_issues_enabled: false

contact_links:
  - name: ğŸ’¡ Discuss an idea
    url: https://github.com/<library_owner>/c<your_library>@latest/discussions/new?category=ideas
    about: Suggest a feature or an improvement.

  - name: â” Ask a question
    url: https://github.com/<library_owner>/<your_library>@latest/discussions/new
    about: Ask questions and discuss with other `<your_library>` users or maintainers.

  - name: ğŸ™ Request help
    url: https://github.com/<library_owner>/<your_library>@latest/discussions/new
    about: Ask the `<your_library>` community for help.
